name: astx
channels:
  - nodefaults
  - conda-forge
dependencies:
  - graphviz >=13
  - openjdk # java is required by asciinet
  - python
  - poetry >=2
  - nodejs # used by semantic-release
  - shellcheck
  - pip
  - pip:
      # distlib issue
      - paginate
